console.log("Avanzar 1 casillero");
console.log("Sacar 1");
console.log("Avnzar 1 casillero");
console.log("sacar 1");
console.log("Avanzar 1  casillero");
console.log("sacar 1");
console.log("Avanzar 1 casillero");
console.log("sacar 1");
console.log("Girar a la derecha");
console.log("Avanzar 1 casillero");
console.log("Sacar 1");
console.log("Avanzar 1 casillero");
console.log("Sacar 1");
console.log("Avanzar 1 casillero");
console.log("Sacar 1");
console.log("Avanzar 1 casillero");
console.log("Sacar 1");
console.log("Avanzar 1 casillero");
console.log("Sacar 1");
