console.log("Hacer milanesas con pure");
console.log("Paso 1");
console.log("Poner en un bolw la carne que compramos para milanesas");
console.log("Paso 2");
console.log("Agregar al bolw 3 o 4 huevos");
console.log("Agregar al bolw 3/4 huevos");
console.log("Paso 3");
console.log("Agregar al bowl condimentos a gusto ");
console.log("Paso 4");
console.log("Dejar reposar por 1 hora");
console.log("Paso 5");
console.log("Preparar una bandeja con pan rallado");
console.log("Paso 6");
console.log("Pasar nuestra carne, ya reposada, por el pan rallado");
console.log("Paso Final");
console.log("Cocinar las Milanesas");
console.log("Elegir a gusto si las hacemos en el horno o fritas");
console.log("A disfrutar!!!! =)");
